rules:
  indentation:
    - 2
    -
      size: 2
  force-element-nesting:
    - 0
  no-important:
    - 0
  no-color-literals:
    - 0
  force-pseudo-nesting:
    - 0
  property-sort-order:
    - 0
  clean-import-paths:
    - 0
  material-theme:
    - 0
