allowBuilds:
  lmdb: true
  esbuild: true
  msgpackr-extract: false
  '@parcel/watcher': false
minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2200.1'
  - '@angular-devkit/core@22.0.1'
  - '@angular-devkit/schematics@22.0.1'
  - '@angular/cli@22.0.1'
  - '@schematics/angular@22.0.1'
  - '@angular/build@22.0.1'
  - '@angular/common@22.0.1'
  - '@angular/compiler-cli@22.0.1'
  - '@angular/compiler@22.0.1'
  - '@angular/core@22.0.1'
  - '@angular/forms@22.0.1'
  - '@angular/platform-browser@22.0.1'
  - '@angular/router@22.0.1'
