{{- if .Values.otelCollector.enabled }}
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "otel-collector-deployment"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "otel-collector"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: "netptune-app"
      app.kubernetes.io/component: "otel-collector"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "netptune-app"
        app.kubernetes.io/component: "otel-collector"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: "otel-collector"
          image: "{{ .Values.otelCollector.image }}"
          args:
            - "--config=/etc/otel-collector/config.yaml"
          ports:
            - name: "otlp-grpc"
              protocol: "TCP"
              containerPort: 4317
            - name: "otlp-http"
              protocol: "TCP"
              containerPort: 4318
            - name: "prometheus"
              protocol: "TCP"
              containerPort: 8889
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: "config"
              mountPath: "/etc/otel-collector"
              readOnly: true
      volumes:
        - name: "config"
          configMap:
            name: "otel-collector-config"
{{- end }}
