{{- if .Values.pgadmin.enabled }}
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "pgadmin-deployment"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "pgadmin"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "netptune-app"
      app.kubernetes.io/component: "pgadmin"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "netptune-app"
        app.kubernetes.io/component: "pgadmin"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      securityContext:
        fsGroup: 5050
        runAsUser: 5050
      containers:
        - name: "pgadmin"
          image: "{{ .Values.pgadmin.image }}"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: "http"
              containerPort: 80
              protocol: "TCP"
          envFrom:
            - secretRef:
                name: "pgadmin-secrets"
          volumeMounts:
            - name: "pgadmin-servers-config"
              mountPath: "/pgadmin4/servers.json"
              subPath: "servers.json"
              readOnly: true
      volumes:
        - name: "pgadmin-servers-config"
          configMap:
            name: "pgadmin-servers-config"
{{- end }}
