{{- if .Values.pgadmin.enabled }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "pgadmin-secrets"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "pgadmin"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  PGADMIN_DEFAULT_EMAIL: "{{ .Values.secrets.pgadmin.admin_email }}"
  PGADMIN_DEFAULT_PASSWORD: "{{ .Values.secrets.pgadmin.admin_password }}"
type: "Opaque"
{{- end }}
