---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "meilisearch-secrets"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "meilisearch"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  MEILI_MASTER_KEY: "{{ .Values.secrets.meilisearch.master_key }}"
type: "Opaque"
