{{- if .Values.grafana.enabled }}
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "grafana-datasource"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "grafana"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: false
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-service:3100
        editable: false
{{- end }}
