version: 2
updates:
  - package-ecosystem: nuget
    directory: /server
    schedule:
      interval: weekly
    groups:
      patch-updates:
        update-types: [patch, minor]

  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    groups:
      patch-updates:
        update-types: [patch, minor]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
