version: '3'
services:
  postgres:
    container_name: netptune-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=
    networks:
      - code-network