---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "api-secrets"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__cache: "cache-service:6379,password={{ .Values.secrets.api.cache_password }}"
  CACHE_PASSWORD: "{{ .Values.secrets.api.cache_password }}"
  CACHE_URI: "valkey://:{{ .Values.secrets.api.cache_password }}@cache-service:6379"
  REDIS_URL: "cache-service:6379,password={{ .Values.secrets.api.cache_password }}"
  ConnectionStrings__postgresdb: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.api.postgres_password }};Database=netptune"
  POSTGRESDB_PASSWORD: "{{ .Values.secrets.api.postgres_password }}"
  POSTGRESDB_URI: "postgresql://postgres:{{ .Values.secrets.api.postgres_password }}@postgres-service:5432/netptune"
  ConnectionStrings__netptune: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.api.postgres_password }};Database=netptune"
  NETPTUNE_SIGNING_KEY: "{{ .Values.secrets.api.signing_key }}"
  NETPTUNE_GITHUB_CLIENT_ID: "{{ .Values.secrets.api.github_client_id }}"
  NETPTUNE_GITHUB_SECRET: "{{ .Values.secrets.api.github_secret }}"
  NETPTUNE_GITHUB_CALLBACK: "{{ .Values.secrets.api.github_callback }}"
  SEND_GRID_API_KEY: "{{ .Values.secrets.api.sendgrid_api_key }}"
  NETPTUNE_S3_BUCKET_NAME: "{{ .Values.secrets.api.s3_bucket_name }}"
  NETPTUNE_S3_REGION: "{{ .Values.secrets.api.s3_region }}"
  NETPTUNE_S3_ACCESS_KEY_ID: "{{ .Values.secrets.api.s3_access_key_id }}"
  NETPTUNE_S3_SECRET_ACCESS_KEY: "{{ .Values.secrets.api.s3_secret_access_key }}"
  NETPTUNE_CLOUDFLARE_EMAIL_TOKEN: "{{.Values.secrets.api.cloudflare_email_token }}"
  NETPTUNE_CLOUDFLARE_ACCOUNT_ID: "{{.Values.secrets.api.cloudflare_account_id }}"
type: "Opaque"
