using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Netptune.SqlSourceGenerator;

[Generator]
public sealed class SqlScriptsGenerator : IIncrementalGenerator
{
    private const string DefaultNamespace = "GeneratedSql";
    private const string ClassName = "SqlScripts";

    private static readonly DiagnosticDescriptor DuplicateIdentifier = new(
        id: "SQLGEN001",
        title: "Duplicate SQL script identifier",
        messageFormat: "Multiple .sql files map to the member name '{0}'; only the first is emitted",
        category: "SqlScripts",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var namespaceProvider = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
            provider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace)
            && !string.IsNullOrWhiteSpace(rootNamespace)
                ? rootNamespace + ".Sql"
                : DefaultNamespace);

        var scripts = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".sql", System.StringComparison.OrdinalIgnoreCase))
            .Select(static (file, cancellationToken) =>
            {
                var fileName = Path.GetFileName(file.Path);
                var sql = file.GetText(cancellationToken)?.ToString() ?? string.Empty;
                return (Identifier: ToIdentifier(Path.GetFileNameWithoutExtension(file.Path)), FileName: fileName, Sql: sql);
            })
            .Collect();

        context.RegisterSourceOutput(scripts.Combine(namespaceProvider), static (productionContext, source) =>
        {
            var (entries, namespaceName) = source;
            if (entries.IsDefaultOrEmpty)
            {
                return;
            }

            productionContext.AddSource(
                $"{ClassName}.g.cs",
                SourceText.From(Emit(namespaceName, entries, productionContext), Encoding.UTF8));
        });
    }

    private static string Emit(
        string namespaceName,
        ImmutableArray<(string Identifier, string FileName, string Sql)> entries,
        SourceProductionContext context)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {namespaceName};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>SQL scripts loaded from .sql files at compile time.</summary>");
        builder.AppendLine($"public static partial class {ClassName}");
        builder.AppendLine("{");

        var seen = new HashSet<string>(System.StringComparer.Ordinal);

        foreach (var entry in entries.OrderBy(static e => e.Identifier, System.StringComparer.Ordinal))
        {
            if (!seen.Add(entry.Identifier))
            {
                context.ReportDiagnostic(Diagnostic.Create(DuplicateIdentifier, Location.None, entry.Identifier));
                continue;
            }

            var literal = SymbolDisplay.FormatLiteral(entry.Sql, quote: true);

            builder.AppendLine($"    /// <summary>Source: <c>{entry.FileName}</c>.</summary>");
            builder.AppendLine($"    public const string {entry.Identifier} = {literal};");
            builder.AppendLine();
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string ToIdentifier(string fileName)
    {
        var builder = new StringBuilder(fileName.Length);
        var capitalizeNext = true;

        foreach (var ch in fileName)
        {
            if (char.IsLetterOrDigit(ch))
            {
                builder.Append(capitalizeNext ? char.ToUpperInvariant(ch) : ch);
                capitalizeNext = false;
            }
            else
            {
                capitalizeNext = true;
            }
        }

        if (builder.Length == 0)
        {
            return "Script";
        }

        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }
}
