{{- if .Values.pgweb.enabled }}
---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "pgweb-ingress"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "pgweb"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - "{{ .Values.pgweb.host }}"
      secretName: "pgweb-tls"
  rules:
    - host: "{{ .Values.pgweb.host }}"
      http:
        paths:
          - path: "/oauth2"
            pathType: "Prefix"
            backend:
              service:
                name: "pgweb-oauth2-proxy-service"
                port:
                  number: 4180
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: "pgweb-oauth2-proxy-service"
                port:
                  number: 4180
{{- end }}
