{{- if .Values.pgweb.enabled }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "pgweb-secrets"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "pgweb"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  DATABASE_URL: "postgres://{{ .Values.config.postgres.POSTGRES_USER }}:{{ .Values.secrets.postgres.postgres_password }}@postgres-service:5432/netptune?sslmode=disable"
type: "Opaque"
{{- end }}
