---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "kafka-service"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "kafka"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "kafka"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: 9092
      targetPort: 9092
    - name: "internal"
      protocol: "TCP"
      port: 9093
      targetPort: 9093
