---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "jobs-config"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "jobs"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.jobs.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ if .Values.otelCollector.enabled }}http://otel-collector-service:4317{{ end }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "{{ if .Values.otelCollector.enabled }}grpc{{ end }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.jobs.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.jobs.port_http }}"
  CACHE_HOST: "{{ .Values.config.jobs.CACHE_HOST }}"
  CACHE_PORT: "{{ .Values.config.jobs.CACHE_PORT }}"
  POSTGRESDB_HOST: "{{ .Values.config.jobs.POSTGRESDB_HOST }}"
  POSTGRESDB_PORT: "{{ .Values.config.jobs.POSTGRESDB_PORT }}"
  POSTGRESDB_USERNAME: "{{ .Values.config.jobs.POSTGRESDB_USERNAME }}"
  POSTGRESDB_JDBCCONNECTIONSTRING: "{{ .Values.config.jobs.POSTGRESDB_JDBCCONNECTIONSTRING }}"
  POSTGRESDB_DATABASENAME: "{{ .Values.config.jobs.POSTGRESDB_DATABASENAME }}"
  ConnectionStrings__nats: "{{ .Values.config.jobs.ConnectionStrings__nats }}"
