---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "jobs-secrets"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "jobs"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__cache: "cache-service:6379,password={{ .Values.secrets.jobs.cache_password }}"
  CACHE_PASSWORD: "{{ .Values.secrets.jobs.cache_password }}"
  CACHE_URI: "valkey://:{{ .Values.secrets.jobs.cache_password }}@cache-service:6379"
  REDIS_URL: "cache-service:6379,password={{ .Values.secrets.jobs.cache_password }}"
  ConnectionStrings__postgresdb: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.jobs.postgres_password }};Database=netptune"
  POSTGRESDB_PASSWORD: "{{ .Values.secrets.jobs.postgres_password }}"
  POSTGRESDB_URI: "postgresql://postgres:{{ .Values.secrets.jobs.postgres_password }}@postgres-service:5432/netptune"
  ConnectionStrings__netptune: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.jobs.postgres_password }};Database=netptune"
  NETPTUNE_SIGNING_KEY: "{{ .Values.secrets.jobs.signing_key }}"
  SEND_GRID_API_KEY: "{{ .Values.secrets.jobs.sendgrid_api_key }}"
  NETPTUNE_S3_BUCKET_NAME: "{{ .Values.secrets.jobs.s3_bucket_name }}"
  NETPTUNE_S3_REGION: "{{ .Values.secrets.jobs.s3_region }}"
  NETPTUNE_S3_ACCESS_KEY_ID: "{{ .Values.secrets.jobs.s3_access_key_id }}"
  NETPTUNE_S3_SECRET_ACCESS_KEY: "{{ .Values.secrets.jobs.s3_secret_access_key }}"
  NETPTUNE_CLOUDFLARE_EMAIL_TOKEN: "{{.Values.secrets.jobs.cloudflare_email_token }}"
  NETPTUNE_CLOUDFLARE_ACCOUNT_ID: "{{.Values.secrets.jobs.cloudflare_account_id }}"
type: "Opaque"
