---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "jobs-service"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "jobs"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "jobs"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: {{ .Values.parameters.jobs.port_http | int }}
      targetPort: {{ .Values.parameters.jobs.port_http | int }}
