{{- if .Values.website.enabled }}
---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "website-ingress"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "website"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - "{{ .Values.website.host }}"
      secretName: "website-tls"
  rules:
    - host: "{{ .Values.website.host }}"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: "website-service"
                port:
                  number: 80
{{- end }}
