using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.EntityFrameworkCore;

using Netptune.Entities.Contexts;

using Polly;
using Polly.Contrib.WaitAndRetry;

namespace Netptune.Entities;

public class HostedDatabaseService : IHostedService
{
    private readonly IServiceScopeFactory ScopeFactory;

    public HostedDatabaseService(IServiceScopeFactory scopeFactory)
    {
        ScopeFactory = scopeFactory;
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        using var scope = ScopeFactory.CreateScope();

        var context = scope.ServiceProvider.GetRequiredService<DataContext>();
        var delay = Backoff.DecorrelatedJitterBackoffV2(medianFirstRetryDelay: TimeSpan.FromSeconds(2), retryCount: 5);

        await Policy
            .Handle<Exception>()
            .WaitAndRetry(delay)
            .Execute(() => context.Database.EnsureCreatedAsync(cancellationToken));

        // EnsureCreated does not evolve an existing database. Keep this additive,
        // idempotent upgrade here until the project adopts EF migrations.
        await context.Database.ExecuteSqlRawAsync(
            "ALTER TABLE project_tasks ADD COLUMN IF NOT EXISTS due_date date",
            cancellationToken);

        await context.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE users ADD COLUMN IF NOT EXISTS user_type integer NOT NULL DEFAULT 0;

            CREATE TABLE IF NOT EXISTS service_accounts (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id text NOT NULL,
                workspace_id integer NOT NULL,
                description character varying(2048),
                created_by_user_id text NOT NULL,
                created_at timestamp without time zone NOT NULL,
                disabled_at timestamp without time zone,
                CONSTRAINT fk_service_accounts_users_user_id
                    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                CONSTRAINT fk_service_accounts_users_created_by_user_id
                    FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
                CONSTRAINT fk_service_accounts_workspaces_workspace_id
                    FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ix_service_accounts_user_id
                ON service_accounts (user_id);
            CREATE INDEX IF NOT EXISTS ix_service_accounts_workspace_id_disabled_at_id
                ON service_accounts (workspace_id, disabled_at, id);

            CREATE TABLE IF NOT EXISTS service_account_owners (
                service_account_id integer NOT NULL,
                user_id text NOT NULL,
                created_at timestamp without time zone NOT NULL,
                CONSTRAINT pk_service_account_owners PRIMARY KEY (service_account_id, user_id),
                CONSTRAINT fk_service_account_owners_service_accounts_service_account_id
                    FOREIGN KEY (service_account_id) REFERENCES service_accounts (id) ON DELETE CASCADE,
                CONSTRAINT fk_service_account_owners_users_user_id
                    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
            );

            CREATE INDEX IF NOT EXISTS ix_service_account_owners_user_id
                ON service_account_owners (user_id);

            CREATE TABLE IF NOT EXISTS api_credentials (
                id uuid PRIMARY KEY,
                service_account_id integer NOT NULL,
                name character varying(128) NOT NULL,
                token_prefix character varying(32) NOT NULL,
                secret_hash bytea NOT NULL,
                scopes jsonb NOT NULL,
                created_at timestamp without time zone NOT NULL,
                created_by_user_id text NOT NULL,
                expires_at timestamp without time zone NOT NULL,
                revoked_at timestamp without time zone,
                last_used_at timestamp without time zone,
                CONSTRAINT fk_api_credentials_service_accounts_service_account_id
                    FOREIGN KEY (service_account_id) REFERENCES service_accounts (id) ON DELETE CASCADE,
                CONSTRAINT fk_api_credentials_users_created_by_user_id
                    FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT
            );

            CREATE UNIQUE INDEX IF NOT EXISTS ix_api_credentials_token_prefix
                ON api_credentials (token_prefix);
            CREATE INDEX IF NOT EXISTS ix_api_credentials_service_account_id_revoked_at_expires_at
                ON api_credentials (service_account_id, revoked_at, expires_at);
            """,
            cancellationToken);
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}
