export enum colors100 {
  red = '#FFCDD2',
  pink = '#F8BBD0',
  purple = '#E1BEE7',
  deepPurple = '#D1C4E9',
  indigo = '#C5CAE9',
  blue = '#BBDEFB',
  lightBlue = '#B3E5FC',
  cyan = '#B2EBF2',
  teal = '#B2DFDB',
  green = '#C8E6C9',
  lightGreen = '#DCEDC8',
  lime = '#F0F4C3',
  yellow = '#FFF9C4',
  amber = '#FFECB3',
  orange = '#FFE0B2',
  deepOrange = '#FFCCBC',
  brown = '#D7CCC8',
  grey = '#F5F5F5',
  blueGrey = '#CFD8DC'
}
