export enum colors100 {
  red = '#FFCDD2',
  pink = '#F8BBD0',
  purple = '#E1BEE7',
  deepPurple = '#D1C4E9',
  indigo = '#C5CAE9',
  blue = '#BBDEFB',
  lightBlue = '#B3E5FC',
  cyan = '#B2EBF2',
  teal = '#B2DFDB',
  green = '#C8E6C9',
  lightGreen = '#DCEDC8',
  lime = '#F0F4C3',
  yellow = '#FFF9C4',
  amber = '#FFECB3',
  orange = '#FFE0B2',
  deepOrange = '#FFCCBC',
  brown = '#D7CCC8',
  grey = '#F5F5F5',
  blueGrey = '#CFD8DC',
}

export const avatarColors = [
  '#FFCDD2',
  '#F8BBD0',
  '#E1BEE7',
  '#D1C4E9',
  '#C5CAE9',
  '#BBDEFB',
  '#B3E5FC',
  '#B2EBF2',
  '#B2DFDB',
  '#C8E6C9',
  '#DCEDC8',
  '#F0F4C3',
  '#FFF9C4',
  '#FFECB3',
  '#FFE0B2',
  '#FFCCBC',
  '#D7CCC8',
  '#F5F5F5',
  '#CFD8DC',
];
