{{- if .Values.dbgate.enabled }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "dbgate-oauth2-proxy-secrets"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "dbgate-oauth2-proxy"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  OAUTH2_PROXY_CLIENT_ID: "{{ .Values.secrets.dbgate.github_client_id }}"
  OAUTH2_PROXY_CLIENT_SECRET: "{{ .Values.secrets.dbgate.github_client_secret }}"
  OAUTH2_PROXY_COOKIE_SECRET: "{{ .Values.secrets.dbgate.cookie_secret }}"
type: "Opaque"
{{- end }}
