{{- if .Values.dbgate.enabled }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "dbgate-secrets"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "dbgate"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  CONNECTIONS: "con1"
  LABEL_con1: "Netptune"
  ENGINE_con1: "postgres@dbgate-plugin-postgres"
  SERVER_con1: "postgres-service"
  PORT_con1: "5432"
  DATABASE_con1: "{{ .Values.config.api.POSTGRESDB_DATABASENAME }}"
  USER_con1: "{{ .Values.config.postgres.POSTGRES_USER }}"
  PASSWORD_con1: "{{ .Values.secrets.postgres.postgres_password }}"
type: "Opaque"
{{- end }}
