<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="CsvHelper" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Netptune.Core\Netptune.Core.csproj" />
    <ProjectReference Include="..\Netptune.Transfer\Netptune.Transfer.csproj" />
  </ItemGroup>

</Project>
