{{- if .Values.loki.enabled }}
---
apiVersion: "apps/v1"
kind: "DaemonSet"
metadata:
  name: "promtail"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "promtail"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "netptune-app"
      app.kubernetes.io/component: "promtail"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "netptune-app"
        app.kubernetes.io/component: "promtail"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      serviceAccountName: "promtail"
      containers:
        - name: "promtail"
          image: "{{ .Values.loki.promtailImage }}"
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          ports:
            - name: "http"
              containerPort: 9080
              protocol: "TCP"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 0
            runAsUser: 0
          volumeMounts:
            - name: "config"
              mountPath: "/etc/promtail"
              readOnly: true
            - name: "pods"
              mountPath: "/var/log/pods"
              readOnly: true
            - name: "positions"
              mountPath: "/run/promtail"
      volumes:
        - name: "config"
          configMap:
            name: "promtail-config"
        - name: "pods"
          hostPath:
            path: "/var/log/pods"
        - name: "positions"
          emptyDir: {}
{{- end }}
