{{- if .Values.loki.enabled }}
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "promtail"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "promtail"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
{{- end }}
