<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Netptune.Core\Netptune.Core.csproj" />
      <ProjectReference Include="..\Netptune.Transfer\Netptune.Transfer.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    </ItemGroup>

</Project>
