---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: netptune-gateway
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      port: 8000
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    {{- if .Values.ingress.enabled }}
    - name: https-netptune
      port: 8443
      protocol: HTTPS
      hostname: "{{ .Values.ingress.host }}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "netptune-tls"
      allowedRoutes:
        namespaces:
          from: Same
    - name: https-app
      port: 8443
      protocol: HTTPS
      hostname: "{{ .Values.ingress.appHost }}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "netptune-app-tls"
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
    {{- if .Values.grafana.enabled }}
    - name: https-grafana
      port: 8443
      protocol: HTTPS
      hostname: "{{ .Values.grafana.host }}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "grafana-tls"
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
    {{- if .Values.headlamp.enabled }}
    - name: https-headlamp
      port: 8443
      protocol: HTTPS
      hostname: "{{ .Values.headlamp.host }}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "headlamp-tls"
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
    {{- if .Values.pgadmin.enabled }}
    - name: https-pgadmin
      port: 8443
      protocol: HTTPS
      hostname: "{{ .Values.pgadmin.host }}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "pgadmin-tls"
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
    {{- if .Values.pgweb.enabled }}
    - name: https-pgweb
      port: 8443
      protocol: HTTPS
      hostname: "{{ .Values.pgweb.host }}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "pgweb-tls"
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
    {{- if .Values.prometheus.enabled }}
    - name: https-prometheus
      port: 8443
      protocol: HTTPS
      hostname: "{{ .Values.prometheus.host }}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "prometheus-tls"
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
    {{- if .Values.website.enabled }}
    - name: https-website
      port: 8443
      protocol: HTTPS
      hostname: "{{ .Values.website.host }}"
      tls:
        mode: Terminate
        certificateRefs:
          - name: "website-tls"
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-to-https-redirect
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  parentRefs:
    - name: netptune-gateway
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
