{{- if or .Values.grafana.enabled .Values.loki.enabled }}
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "monitoring-pvc"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.persistence.monitoring.size }}"
{{- end }}
