---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "client-service"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "client"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "client"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 80
      targetPort: 80
