create table if not exists user_preference_values (
    id integer generated by default as identity primary key,
    user_id text not null,
    workspace_id integer null,
    key character varying(256) not null,
    value jsonb not null,
    created_at timestamp without time zone not null,
    updated_at timestamp without time zone not null,
    constraint fk_user_preference_values_users_user_id
        foreign key (user_id) references users (id) on delete cascade,
    constraint fk_user_preference_values_workspaces_workspace_id
        foreign key (workspace_id) references workspaces (id) on delete cascade
);

create unique index if not exists ix_user_preference_values_user_key_global
    on user_preference_values (user_id, key)
    where workspace_id is null;

create unique index if not exists ix_user_preference_values_user_workspace_key
    on user_preference_values (user_id, workspace_id, key)
    where workspace_id is not null;

create table if not exists command_palette_recent_items (
    id integer generated by default as identity primary key,
    user_id text not null,
    workspace_id integer not null,
    type character varying(64) not null,
    entity_id character varying(128) null,
    title character varying(512) not null,
    url character varying(2048) not null,
    last_accessed_at timestamp without time zone not null,
    constraint fk_command_palette_recent_items_users_user_id
        foreign key (user_id) references users (id) on delete cascade,
    constraint fk_command_palette_recent_items_workspaces_workspace_id
        foreign key (workspace_id) references workspaces (id) on delete cascade
);

create unique index if not exists ix_command_palette_recent_items_user_id_workspace_id_url
    on command_palette_recent_items (user_id, workspace_id, url);

create index if not exists ix_command_palette_recent_items_workspace_recent
    on command_palette_recent_items (user_id, workspace_id, last_accessed_at);

create index if not exists ix_command_palette_recent_items_global_recent
    on command_palette_recent_items (user_id, last_accessed_at);
