-- Tables backing the AI assistant.
-- New databases get these from EnsureCreated; an existing database needs this script.

CREATE TABLE IF NOT EXISTS user_ai_credentials (
    id uuid NOT NULL,
    user_id text NOT NULL,
    provider integer NOT NULL,
    label character varying(128) NOT NULL,
    secret bytea NOT NULL,
    secret_hint character varying(8) NOT NULL,
    model character varying(128),
    created_at timestamp with time zone NOT NULL,
    last_used_at timestamp with time zone,
    CONSTRAINT pk_user_ai_credentials PRIMARY KEY (id),
    CONSTRAINT fk_user_ai_credentials_app_user_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_conversations (
    id uuid NOT NULL,
    user_id text NOT NULL,
    title character varying(256) NOT NULL,
    provider integer NOT NULL,
    model character varying(128) NOT NULL,
    last_message_at timestamp with time zone NOT NULL,
    message_count integer NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone,
    created_by_user_id text,
    modified_by_user_id text,
    deleted_by_user_id text,
    owner_id text,
    workspace_id integer NOT NULL,
    CONSTRAINT pk_ai_conversations PRIMARY KEY (id),
    CONSTRAINT fk_ai_conversations_app_user_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ai_conversations_app_user_deleted_by_user_id FOREIGN KEY (deleted_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ai_conversations_app_user_modified_by_user_id FOREIGN KEY (modified_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ai_conversations_app_user_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ai_conversations_app_user_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ai_conversations_workspaces_workspace_id FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS ai_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    conversation_id uuid NOT NULL,
    sequence integer NOT NULL,
    role integer NOT NULL,
    content jsonb NOT NULL,
    provider_payload jsonb,
    provider integer NOT NULL,
    model character varying(128) NOT NULL,
    status integer NOT NULL,
    finish_reason character varying(64),
    error text,
    input_tokens integer NOT NULL,
    output_tokens integer NOT NULL,
    cache_read_tokens integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_ai_messages PRIMARY KEY (id),
    CONSTRAINT fk_ai_messages_ai_conversations_conversation_id FOREIGN KEY (conversation_id) REFERENCES ai_conversations (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_change_sets (
    id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    message_id bigint NOT NULL,
    user_id text NOT NULL,
    status integer NOT NULL,
    correlation_id uuid NOT NULL,
    applied_at timestamp with time zone,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
    updated_at timestamp with time zone,
    created_by_user_id text,
    modified_by_user_id text,
    deleted_by_user_id text,
    owner_id text,
    workspace_id integer NOT NULL,
    CONSTRAINT pk_ai_change_sets PRIMARY KEY (id),
    CONSTRAINT fk_ai_change_sets_ai_conversations_conversation_id FOREIGN KEY (conversation_id) REFERENCES ai_conversations (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_change_sets_app_user_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ai_change_sets_app_user_deleted_by_user_id FOREIGN KEY (deleted_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ai_change_sets_app_user_modified_by_user_id FOREIGN KEY (modified_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ai_change_sets_app_user_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ai_change_sets_workspaces_workspace_id FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS ai_proposed_changes (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    change_set_id uuid NOT NULL,
    sequence integer NOT NULL,
    tool_name character varying(64) NOT NULL,
    entity_type character varying(64) NOT NULL,
    entity_id integer,
    ref_key character varying(32),
    summary character varying(512) NOT NULL,
    fields jsonb NOT NULL,
    payload jsonb NOT NULL,
    validation_status integer NOT NULL,
    validation_message text,
    apply_status integer NOT NULL,
    apply_error text,
    applied_entity_id integer,
    CONSTRAINT pk_ai_proposed_changes PRIMARY KEY (id),
    CONSTRAINT fk_ai_proposed_changes_ai_change_sets_change_set_id FOREIGN KEY (change_set_id) REFERENCES ai_change_sets (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ai_tool_invocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    conversation_id uuid NOT NULL,
    message_id bigint NOT NULL,
    tool_name character varying(64) NOT NULL,
    arguments jsonb NOT NULL,
    result jsonb,
    result_truncated boolean NOT NULL,
    status integer NOT NULL,
    error text,
    duration_milliseconds integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_ai_tool_invocations PRIMARY KEY (id),
    CONSTRAINT fk_ai_tool_invocations_ai_messages_message_id FOREIGN KEY (message_id) REFERENCES ai_messages (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_ai_change_sets_conversation_id_status ON ai_change_sets (conversation_id, status);
CREATE INDEX IF NOT EXISTS ix_ai_change_sets_created_by_user_id ON ai_change_sets (created_by_user_id);
CREATE INDEX IF NOT EXISTS ix_ai_change_sets_deleted_by_user_id ON ai_change_sets (deleted_by_user_id);
CREATE INDEX IF NOT EXISTS ix_ai_change_sets_is_deleted ON ai_change_sets (is_deleted);
CREATE INDEX IF NOT EXISTS ix_ai_change_sets_modified_by_user_id ON ai_change_sets (modified_by_user_id);
CREATE INDEX IF NOT EXISTS ix_ai_change_sets_owner_id ON ai_change_sets (owner_id);
CREATE INDEX IF NOT EXISTS ix_ai_change_sets_workspace_id ON ai_change_sets (workspace_id);
CREATE INDEX IF NOT EXISTS ix_ai_conversations_created_by_user_id ON ai_conversations (created_by_user_id);
CREATE INDEX IF NOT EXISTS ix_ai_conversations_deleted_by_user_id ON ai_conversations (deleted_by_user_id);
CREATE INDEX IF NOT EXISTS ix_ai_conversations_is_deleted ON ai_conversations (is_deleted);
CREATE INDEX IF NOT EXISTS ix_ai_conversations_modified_by_user_id ON ai_conversations (modified_by_user_id);
CREATE INDEX IF NOT EXISTS ix_ai_conversations_owner_id ON ai_conversations (owner_id);
CREATE INDEX IF NOT EXISTS ix_ai_conversations_user_id ON ai_conversations (user_id);
CREATE INDEX IF NOT EXISTS ix_ai_conversations_workspace_user_last_message ON ai_conversations (workspace_id, user_id, is_deleted, last_message_at);
CREATE UNIQUE INDEX IF NOT EXISTS ix_ai_messages_conversation_sequence ON ai_messages (conversation_id, sequence);
CREATE UNIQUE INDEX IF NOT EXISTS ix_ai_proposed_changes_change_set_sequence ON ai_proposed_changes (change_set_id, sequence);
CREATE INDEX IF NOT EXISTS ix_ai_tool_invocations_conversation_id ON ai_tool_invocations (conversation_id);
CREATE INDEX IF NOT EXISTS ix_ai_tool_invocations_message_id ON ai_tool_invocations (message_id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_user_ai_credentials_user_id_provider ON user_ai_credentials (user_id, provider);
