CREATE TABLE IF NOT EXISTS automation_rules (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id integer NOT NULL REFERENCES workspaces(id) ON DELETE RESTRICT,
    name character varying(256) NOT NULL,
    is_enabled boolean NOT NULL DEFAULT TRUE,
    execution_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    trigger_type integer NOT NULL,
    trigger_config jsonb NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL,
    created_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    modified_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    deleted_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    owner_id text NULL REFERENCES users(id) ON DELETE RESTRICT
);

ALTER TABLE automation_rules
    ADD COLUMN IF NOT EXISTS execution_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS ix_automation_rules_is_deleted
    ON automation_rules(is_deleted);

CREATE INDEX IF NOT EXISTS ix_automation_rules_workspace_enabled
    ON automation_rules(workspace_id, is_enabled);

CREATE TABLE IF NOT EXISTS automation_actions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    automation_rule_id integer NOT NULL REFERENCES automation_rules(id) ON DELETE CASCADE,
    type integer NOT NULL,
    sort_order integer NOT NULL,
    config jsonb NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL,
    created_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    modified_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    deleted_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    owner_id text NULL REFERENCES users(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_automation_actions_is_deleted
    ON automation_actions(is_deleted);

CREATE INDEX IF NOT EXISTS ix_automation_actions_rule_sort_order
    ON automation_actions(automation_rule_id, sort_order);

CREATE TABLE IF NOT EXISTS automation_runs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    automation_rule_id integer NOT NULL REFERENCES automation_rules(id) ON DELETE CASCADE,
    entity_id integer NULL,
    entity_type integer NULL,
    trigger_type integer NOT NULL,
    status integer NOT NULL,
    idempotency_key character varying(512) NOT NULL,
    message character varying(2048) NULL,
    context jsonb NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL,
    created_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    modified_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    deleted_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    owner_id text NULL REFERENCES users(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_automation_runs_is_deleted
    ON automation_runs(is_deleted);

CREATE UNIQUE INDEX IF NOT EXISTS ix_automation_runs_idempotency_key
    ON automation_runs(idempotency_key);

CREATE INDEX IF NOT EXISTS ix_automation_runs_rule_created
    ON automation_runs(automation_rule_id, created_at);

CREATE TABLE IF NOT EXISTS automation_action_results (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    automation_run_id integer NOT NULL REFERENCES automation_runs(id) ON DELETE CASCADE,
    automation_action_id integer NOT NULL,
    action_type integer NOT NULL,
    sort_order integer NOT NULL,
    status integer NOT NULL,
    idempotency_key character varying(768) NOT NULL,
    started_at timestamp with time zone NULL,
    completed_at timestamp with time zone NULL,
    message character varying(2048) NULL,
    output jsonb NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL,
    created_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    modified_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    deleted_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    owner_id text NULL REFERENCES users(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_automation_action_results_is_deleted
    ON automation_action_results(is_deleted);

CREATE UNIQUE INDEX IF NOT EXISTS ix_automation_action_results_idempotency_key
    ON automation_action_results(idempotency_key);

CREATE INDEX IF NOT EXISTS ix_automation_action_results_run_sort_order
    ON automation_action_results(automation_run_id, sort_order);

CREATE TABLE IF NOT EXISTS scheduled_automation_actions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    automation_rule_id integer NOT NULL REFERENCES automation_rules(id) ON DELETE CASCADE,
    automation_action_id integer NOT NULL REFERENCES automation_actions(id) ON DELETE CASCADE,
    task_id integer NOT NULL REFERENCES project_tasks(id) ON DELETE CASCADE,
    action_type integer NOT NULL,
    status integer NOT NULL,
    expected_status_id integer NOT NULL,
    execute_at timestamp with time zone NOT NULL,
    processed_at timestamp with time zone NULL,
    attempt_count integer NOT NULL DEFAULT 0,
    claim_id uuid NULL,
    lease_expires_at timestamp with time zone NULL,
    last_error character varying(2048) NULL,
    trigger_context jsonb NULL,
    idempotency_key character varying(768) NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone NULL,
    created_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    modified_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    deleted_by_user_id text NULL REFERENCES users(id) ON DELETE RESTRICT,
    owner_id text NULL REFERENCES users(id) ON DELETE RESTRICT
);

ALTER TABLE scheduled_automation_actions
    ADD COLUMN IF NOT EXISTS attempt_count integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS claim_id uuid NULL,
    ADD COLUMN IF NOT EXISTS lease_expires_at timestamp with time zone NULL,
    ADD COLUMN IF NOT EXISTS last_error character varying(2048) NULL,
    ADD COLUMN IF NOT EXISTS trigger_context jsonb NULL;

CREATE INDEX IF NOT EXISTS ix_scheduled_automation_actions_is_deleted
    ON scheduled_automation_actions(is_deleted);

CREATE UNIQUE INDEX IF NOT EXISTS ix_scheduled_automation_actions_idempotency_key
    ON scheduled_automation_actions(idempotency_key);

CREATE INDEX IF NOT EXISTS ix_scheduled_automation_actions_status_execute_at
    ON scheduled_automation_actions(status, execute_at);

CREATE INDEX IF NOT EXISTS ix_scheduled_automation_actions_status_lease_expires_at
    ON scheduled_automation_actions(status, lease_expires_at);

CREATE INDEX IF NOT EXISTS ix_scheduled_automation_actions_task_status
    ON scheduled_automation_actions(task_id, status);

ALTER TABLE flags
    ADD COLUMN IF NOT EXISTS entity_type integer NULL,
    ADD COLUMN IF NOT EXISTS entity_id integer NULL,
    ADD COLUMN IF NOT EXISTS automation_rule_id integer NULL;

CREATE INDEX IF NOT EXISTS ix_flags_workspace_entity
    ON flags(workspace_id, entity_type, entity_id);

CREATE UNIQUE INDEX IF NOT EXISTS ix_flags_automation_rule_entity
    ON flags(automation_rule_id, entity_type, entity_id)
    WHERE automation_rule_id IS NOT NULL
      AND entity_type IS NOT NULL
      AND entity_id IS NOT NULL;
