-- Pinned tasks: a task kept in view at one of four scopes.
-- New databases get this from EnsureCreated; an existing database needs this script.
-- Constraint and index names match what EnsureCreated produces so both paths land on one schema.

CREATE TABLE IF NOT EXISTS task_pins
(
    id                  integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_task_id     integer NOT NULL,
    scope               integer NOT NULL,
    scope_entity_id     integer NOT NULL,
    sort_order          double precision NOT NULL DEFAULT 0.0,
    is_deleted          boolean NOT NULL DEFAULT FALSE,
    created_at          timestamp without time zone NOT NULL DEFAULT (NOW()),
    updated_at          timestamp without time zone NULL,
    created_by_user_id  text NULL,
    modified_by_user_id text NULL,
    deleted_by_user_id  text NULL,
    owner_id            text NULL,
    workspace_id        integer NOT NULL,
    CONSTRAINT pk_task_pins PRIMARY KEY (id),
    CONSTRAINT fk_task_pins_app_user_created_by_user_id
        FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_pins_app_user_deleted_by_user_id
        FOREIGN KEY (deleted_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_pins_app_user_modified_by_user_id
        FOREIGN KEY (modified_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_pins_app_user_owner_id
        FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_pins_project_tasks_project_task_id
        FOREIGN KEY (project_task_id) REFERENCES project_tasks (id) ON DELETE CASCADE,
    CONSTRAINT fk_task_pins_workspaces_workspace_id
        FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_task_pins_created_by_user_id  ON task_pins (created_by_user_id);
CREATE INDEX IF NOT EXISTS ix_task_pins_deleted_by_user_id  ON task_pins (deleted_by_user_id);
CREATE INDEX IF NOT EXISTS ix_task_pins_is_deleted          ON task_pins (is_deleted);
CREATE INDEX IF NOT EXISTS ix_task_pins_modified_by_user_id ON task_pins (modified_by_user_id);
CREATE INDEX IF NOT EXISTS ix_task_pins_owner_id            ON task_pins (owner_id);
CREATE INDEX IF NOT EXISTS ix_task_pins_project_task_id     ON task_pins (project_task_id);

CREATE INDEX IF NOT EXISTS ix_task_pins_workspace_id_scope_scope_entity_id
    ON task_pins (workspace_id, scope, scope_entity_id);

-- One personal pin per (task, person); one shared pin per (task, scope, target).
CREATE UNIQUE INDEX IF NOT EXISTS ix_task_pins_project_task_id_scope_entity_id_created_by_user_id
    ON task_pins (project_task_id, scope_entity_id, created_by_user_id)
    WHERE scope = 0 AND NOT is_deleted;

CREATE UNIQUE INDEX IF NOT EXISTS ix_task_pins_project_task_id_scope_scope_entity_id
    ON task_pins (project_task_id, scope, scope_entity_id)
    WHERE scope <> 0 AND NOT is_deleted;
