-- Per-scope notification subscriptions: a person opting in to task activity on one project, board,
-- board group or sprint. New databases get this from EnsureCreated; an existing database needs this
-- script. Constraint and index names match what EnsureCreated produces so both paths land on one schema.

CREATE TABLE IF NOT EXISTS notification_subscriptions
(
    id                  integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             text NOT NULL,
    scope               integer NOT NULL,
    scope_entity_id     integer NOT NULL,
    events              integer NOT NULL,
    is_deleted          boolean NOT NULL DEFAULT FALSE,
    created_at          timestamp without time zone NOT NULL DEFAULT (NOW()),
    updated_at          timestamp without time zone NULL,
    created_by_user_id  text NULL,
    modified_by_user_id text NULL,
    deleted_by_user_id  text NULL,
    owner_id            text NULL,
    workspace_id        integer NOT NULL,
    CONSTRAINT pk_notification_subscriptions PRIMARY KEY (id),
    CONSTRAINT fk_notification_subscriptions_app_user_created_by_user_id
        FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_notification_subscriptions_app_user_deleted_by_user_id
        FOREIGN KEY (deleted_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_notification_subscriptions_app_user_modified_by_user_id
        FOREIGN KEY (modified_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_notification_subscriptions_app_user_owner_id
        FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_notification_subscriptions_users_user_id
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_subscriptions_workspaces_workspace_id
        FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_notification_subscriptions_created_by_user_id  ON notification_subscriptions (created_by_user_id);
CREATE INDEX IF NOT EXISTS ix_notification_subscriptions_deleted_by_user_id  ON notification_subscriptions (deleted_by_user_id);
CREATE INDEX IF NOT EXISTS ix_notification_subscriptions_is_deleted          ON notification_subscriptions (is_deleted);
CREATE INDEX IF NOT EXISTS ix_notification_subscriptions_modified_by_user_id ON notification_subscriptions (modified_by_user_id);
CREATE INDEX IF NOT EXISTS ix_notification_subscriptions_owner_id            ON notification_subscriptions (owner_id);
CREATE INDEX IF NOT EXISTS ix_notification_subscriptions_user_id             ON notification_subscriptions (user_id);
CREATE INDEX IF NOT EXISTS ix_notification_subscriptions_workspace_id        ON notification_subscriptions (workspace_id);

-- Fan-out reads every subscription pointing at the scopes one task event touches.
CREATE INDEX IF NOT EXISTS ix_notification_subscriptions_scope_target
    ON notification_subscriptions (workspace_id, scope, scope_entity_id);

-- One live subscription per person per scope target.
CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_subscriptions_user_scope_target
    ON notification_subscriptions (workspace_id, user_id, scope, scope_entity_id)
    WHERE NOT is_deleted;
