-- Saved task views: a stored query plus the display configuration it renders with.
-- New databases get this from EnsureCreated; an existing database needs this script.

CREATE TABLE IF NOT EXISTS task_views
(
    id                  integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                character varying(256) NOT NULL,
    description         character varying(1024) NULL,
    slug                character varying(128) NOT NULL,
    icon                character varying(64) NULL,
    definition          jsonb NOT NULL,
    is_shared           boolean NOT NULL DEFAULT FALSE,
    is_deleted          boolean NOT NULL DEFAULT FALSE,
    created_at          timestamp without time zone NOT NULL DEFAULT now(),
    updated_at          timestamp without time zone NULL,
    created_by_user_id  text NULL,
    modified_by_user_id text NULL,
    deleted_by_user_id  text NULL,
    owner_id            text NULL,
    workspace_id        integer NOT NULL,
    CONSTRAINT task_views_pkey PRIMARY KEY (id),
    CONSTRAINT fk_task_views_app_user_created_by_user_id
        FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_views_app_user_modified_by_user_id
        FOREIGN KEY (modified_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_views_app_user_deleted_by_user_id
        FOREIGN KEY (deleted_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_views_app_user_owner_id
        FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_views_workspaces_workspace_id
        FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_task_views_created_by_user_id ON task_views (created_by_user_id);
CREATE INDEX IF NOT EXISTS ix_task_views_modified_by_user_id ON task_views (modified_by_user_id);
CREATE INDEX IF NOT EXISTS ix_task_views_deleted_by_user_id ON task_views (deleted_by_user_id);
CREATE INDEX IF NOT EXISTS ix_task_views_owner_id ON task_views (owner_id);
CREATE INDEX IF NOT EXISTS ix_task_views_is_deleted ON task_views (is_deleted);
CREATE UNIQUE INDEX IF NOT EXISTS ix_task_views_workspace_id_slug ON task_views (workspace_id, slug);
