-- Migrates the legacy activity log schema to the generic event ledger.
--
-- Run this once while every Netptune application and worker is stopped. The
-- transaction takes exclusive locks on the affected tables so old and new
-- writers cannot produce a partially migrated ledger.
--
-- Historical activity logs remain audit-retention events. They are deliberately
-- not converted into permanent reporting facts because the legacy payload does
-- not contain reliable transition or sprint-baseline data.

BEGIN;

SELECT pg_advisory_xact_lock(hashtext('netptune:migrate-activity-ledger'));

DO $$
DECLARE
    invalid_entity_types text;
BEGIN
    IF to_regclass('public.activity_logs') IS NULL THEN
        RAISE EXCEPTION 'Cannot migrate: public.activity_logs does not exist';
    END IF;

    IF to_regclass('public.activity_entries') IS NULL THEN
        RAISE EXCEPTION 'Cannot migrate: public.activity_entries does not exist';
    END IF;

    IF to_regclass('public.notifications') IS NULL THEN
        RAISE EXCEPTION 'Cannot migrate: public.notifications does not exist';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'activity_entries'
          AND column_name = 'last_activity_log_id'
    ) THEN
        RAISE EXCEPTION 'Cannot migrate: activity_entries.last_activity_log_id does not exist';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'notifications'
          AND column_name = 'activity_log_id'
    ) THEN
        RAISE EXCEPTION 'Cannot migrate: notifications.activity_log_id does not exist';
    END IF;

    SELECT string_agg(entity_type::text, ', ' ORDER BY entity_type)
    INTO invalid_entity_types
    FROM (
        SELECT DISTINCT entity_type
        FROM public.activity_logs
        WHERE entity_type NOT BETWEEN 0 AND 11
    ) invalid_values;

    IF invalid_entity_types IS NOT NULL THEN
        RAISE EXCEPTION 'Cannot migrate: unexpected activity_logs.entity_type value(s): %', invalid_entity_types;
    END IF;
END
$$;

LOCK TABLE public.activity_logs IN ACCESS EXCLUSIVE MODE;
LOCK TABLE public.activity_entries IN ACCESS EXCLUSIVE MODE;
LOCK TABLE public.notifications IN ACCESS EXCLUSIVE MODE;
LOCK TABLE public.sprints IN ACCESS EXCLUSIVE MODE;

CREATE TABLE IF NOT EXISTS public.event_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id uuid NOT NULL,
    workspace_id integer NULL,
    event_key character varying(128) NOT NULL,
    schema_version smallint NOT NULL,
    subject_type character varying(64) NULL,
    subject_id character varying(128) NULL,
    subject_sequence bigint NULL,
    occurred_at timestamp without time zone NOT NULL,
    recorded_at timestamp without time zone NOT NULL,
    actor_user_id text NULL,
    correlation_id uuid NULL,
    causation_event_id uuid NULL,
    ip_address inet NULL,
    user_agent character varying(1024) NULL,
    retention_class character varying(32) NOT NULL,
    payload jsonb NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_event_records_event_id
    ON public.event_records(event_id);

CREATE UNIQUE INDEX IF NOT EXISTS ix_event_records_subject_sequence
    ON public.event_records(workspace_id, subject_type, subject_id, subject_sequence);

CREATE INDEX IF NOT EXISTS ix_event_records_workspace_occurred_id
    ON public.event_records(workspace_id, occurred_at, id);

CREATE INDEX IF NOT EXISTS ix_event_records_workspace_key_occurred_id
    ON public.event_records(workspace_id, event_key, occurred_at, id);

CREATE TABLE IF NOT EXISTS public.event_references (
    event_record_id bigint NOT NULL,
    role character varying(32) NOT NULL,
    entity_type character varying(64) NOT NULL,
    entity_id character varying(128) NOT NULL,
    CONSTRAINT pk_event_references
        PRIMARY KEY (event_record_id, role, entity_type, entity_id),
    CONSTRAINT fk_event_references_event_records_event_record_id
        FOREIGN KEY (event_record_id)
        REFERENCES public.event_records(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_event_references_reverse_lookup
    ON public.event_references(entity_type, entity_id, role, event_record_id);

CREATE TABLE IF NOT EXISTS public.event_stream_heads (
    workspace_id integer NOT NULL,
    subject_type character varying(64) NOT NULL,
    subject_id character varying(128) NOT NULL,
    current_sequence bigint NOT NULL,
    CONSTRAINT pk_event_stream_heads
        PRIMARY KEY (workspace_id, subject_type, subject_id)
);

CREATE TABLE IF NOT EXISTS public.event_outbox (
    event_record_id bigint NOT NULL,
    available_at timestamp without time zone NOT NULL,
    attempt_count integer NOT NULL,
    lease_id uuid NULL,
    lease_expires_at timestamp without time zone NULL,
    last_error text NULL,
    dead_lettered_at timestamp without time zone NULL,
    CONSTRAINT pk_event_outbox PRIMARY KEY (event_record_id),
    CONSTRAINT fk_event_outbox_event_records_event_record_id
        FOREIGN KEY (event_record_id)
        REFERENCES public.event_records(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_event_outbox_available_at_lease_expires_at
    ON public.event_outbox(available_at, lease_expires_at);

CREATE INDEX IF NOT EXISTS ix_event_outbox_dead_lettered_at
    ON public.event_outbox(dead_lettered_at);

INSERT INTO public.event_records (
      event_id
    , workspace_id
    , event_key
    , schema_version
    , subject_type
    , subject_id
    , subject_sequence
    , occurred_at
    , recorded_at
    , actor_user_id
    , correlation_id
    , causation_event_id
    , ip_address
    , user_agent
    , retention_class
    , payload
)
SELECT
      log.event_id
    , log.workspace_id
    , 'entity.activity-recorded'
    , 1
    , CASE log.entity_type
          WHEN 0 THEN 'user'
          WHEN 1 THEN 'workspace'
          WHEN 2 THEN 'project'
          WHEN 3 THEN 'board'
          WHEN 4 THEN 'boardgroup'
          WHEN 5 THEN 'task'
          WHEN 6 THEN 'comment'
          WHEN 7 THEN 'tag'
          WHEN 8 THEN 'sprint'
          WHEN 9 THEN 'status'
          WHEN 10 THEN 'relationtype'
          WHEN 11 THEN 'workspacefile'
      END
    , log.entity_id::text
    , NULL
    , log.occurred_at
    , COALESCE(log.created_at, log.occurred_at)
    , log.user_id
    , NULL
    , NULL
    , NULL
    , NULL
    , 'audit'
    , CASE
          WHEN jsonb_typeof(log.meta) = 'object' THEN log.meta
          WHEN log.meta IS NULL THEN '{}'::jsonb
          ELSE jsonb_build_object('legacyMeta', log.meta)
      END
      || jsonb_build_object(
          'activityType', log.type,
          'workspaceSlug', log.workspace_slug,
          'projectSlug', log.project_slug,
          'boardSlug', log.board_slug,
          'legacyActivityLogId', log.id
      )
FROM public.activity_logs log
ON CONFLICT (event_id) DO NOTHING;

DO $$
DECLARE
    missing_event_count bigint;
BEGIN
    SELECT count(*)
    INTO missing_event_count
    FROM public.activity_logs log
    LEFT JOIN public.event_records record ON record.event_id = log.event_id
    WHERE record.id IS NULL;

    IF missing_event_count > 0 THEN
        RAISE EXCEPTION 'Event migration failed: % activity log rows have no event record', missing_event_count;
    END IF;
END
$$;

INSERT INTO public.event_references (
      event_record_id
    , role
    , entity_type
    , entity_id
)
SELECT record.id, reference.role, reference.entity_type, reference.entity_id
FROM public.activity_logs log
INNER JOIN public.event_records record ON record.event_id = log.event_id
CROSS JOIN LATERAL (
    VALUES
          ('scope', 'project', log.project_id::text)
        , ('scope', 'board', log.board_id::text)
        , ('scope', 'boardgroup', log.board_group_id::text)
        , ('parent', 'task', log.task_id::text)
) reference(role, entity_type, entity_id)
WHERE reference.entity_id IS NOT NULL
ON CONFLICT DO NOTHING;

ALTER TABLE public.activity_entries
    ADD COLUMN last_event_record_id bigint NULL;

UPDATE public.activity_entries entry
SET last_event_record_id = record.id
FROM public.activity_logs log
INNER JOIN public.event_records record ON record.event_id = log.event_id
WHERE entry.last_activity_log_id = log.id;

DO $$
DECLARE
    actionable_orphan_count bigint;
BEGIN
    SELECT count(*)
    INTO actionable_orphan_count
    FROM public.activity_entries
    WHERE last_event_record_id IS NULL
      AND (is_open OR notified_at IS NULL);

    IF actionable_orphan_count > 0 THEN
        RAISE EXCEPTION 'Activity entry migration failed: % open or pending entries reference archived activity logs', actionable_orphan_count;
    END IF;
END
$$;

UPDATE public.activity_entries
SET last_event_record_id = 0
WHERE last_event_record_id IS NULL;

ALTER TABLE public.activity_entries
    ALTER COLUMN last_event_record_id SET NOT NULL,
    DROP COLUMN last_activity_log_id;

ALTER TABLE public.notifications
    ADD COLUMN event_record_id bigint NULL;

UPDATE public.notifications notification
SET event_record_id = record.id
FROM public.activity_logs log
INNER JOIN public.event_records record ON record.event_id = log.event_id
WHERE notification.activity_log_id = log.id;

DO $$
DECLARE
    orphan_notification_count bigint;
BEGIN
    SELECT count(*)
    INTO orphan_notification_count
    FROM public.notifications
    WHERE event_record_id IS NULL;

    IF orphan_notification_count > 0 THEN
        RAISE EXCEPTION 'Notification migration failed: % notifications have no event record', orphan_notification_count;
    END IF;
END
$$;

ALTER TABLE public.notifications
    DROP CONSTRAINT IF EXISTS fk_notifications_activity_logs_activity_log_id;

DROP INDEX IF EXISTS public.ix_notifications_activity_log_id;

ALTER TABLE public.notifications
    ALTER COLUMN event_record_id SET NOT NULL,
    ADD CONSTRAINT fk_notifications_event_records_event_record_id
        FOREIGN KEY (event_record_id)
        REFERENCES public.event_records(id)
        ON DELETE CASCADE,
    DROP COLUMN activity_log_id;

CREATE INDEX IF NOT EXISTS ix_notifications_event_record_id
    ON public.notifications(event_record_id);

ALTER TABLE public.sprints
    ADD COLUMN IF NOT EXISTS started_at timestamp without time zone NULL;

DROP TABLE public.activity_logs;

COMMIT;
