-- Reporting query-plan benchmark (Phase 4 hardening).
--
-- Reproduces the event-ledger schema + indexes (mirroring EventRecordEntityMap /
-- EventReferenceEntityMap) at volume and EXPLAINs the hot reporting query shapes, so the
-- flow / burndown / coverage plans can be re-checked as the ledger grows.
--
-- Run against a throwaway Postgres (do NOT point at a real database):
--   docker run -d --name pg-bench -e POSTGRES_PASSWORD=bench -e POSTGRES_DB=bench postgres:18.3
--   docker cp server/scripts/reporting-query-plan-bench.sql pg-bench:/tmp/bench.sql
--   docker exec pg-bench psql -U postgres -d bench -f /tmp/bench.sql
--   docker rm -f pg-bench
--
-- Findings (600k events, ~120k in the target workspace):
--   * flow (single project)   index scans both sides, fast
--   * burndown (UNION)        subject-sequence + reference reverse-lookup, ~sub-ms
--                             (was a full workspace-event scan when written as a single OR)
--   * coverageStart           still scans the workspace's permanent events in the all-projects
--                             case; the cost is the near-total event_references match, which an
--                             event_records index does not remove. Left as a follow-up (precompute
--                             a per-workspace coverage timestamp) rather than adding a low-value index.

DROP TABLE IF EXISTS event_references;
DROP TABLE IF EXISTS event_records;

CREATE TABLE event_records (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id           uuid NOT NULL,
  workspace_id       int NULL,
  event_key          varchar(128) NOT NULL,
  schema_version     smallint NOT NULL,
  subject_type       varchar(64) NULL,
  subject_id         varchar(128) NULL,
  subject_sequence   bigint NULL,
  occurred_at        timestamptz NOT NULL,
  recorded_at        timestamptz NOT NULL,
  retention_class    varchar(32) NOT NULL,
  payload            jsonb NOT NULL
);

CREATE TABLE event_references (
  event_record_id bigint NOT NULL REFERENCES event_records(id) ON DELETE CASCADE,
  role            varchar(32) NOT NULL,
  entity_type     varchar(64) NOT NULL,
  entity_id       varchar(128) NOT NULL,
  PRIMARY KEY (event_record_id, role, entity_type, entity_id)
);

CREATE UNIQUE INDEX ix_event_records_event_id ON event_records (event_id);
CREATE INDEX ix_event_records_workspace_occurred_id ON event_records (workspace_id, occurred_at, id);
CREATE UNIQUE INDEX ix_event_records_subject_sequence ON event_records (workspace_id, subject_type, subject_id, subject_sequence);
CREATE INDEX ix_event_records_workspace_key_occurred_id ON event_records (workspace_id, event_key, occurred_at, id);
CREATE INDEX ix_event_references_reverse_lookup ON event_references (entity_type, entity_id, role, event_record_id);

INSERT INTO event_records
  (event_id, workspace_id, event_key, schema_version, subject_type, subject_id, subject_sequence,
   occurred_at, recorded_at, retention_class, payload)
SELECT
  gen_random_uuid(),
  1 + (g % 5),
  (ARRAY['entity.created','entity.field-transitioned','scope.member-changed','scope.lifecycle-transitioned'])[1 + (g % 4)],
  1,
  (ARRAY['task','task','task','sprint'])[1 + (g % 4)],
  ((g % 40000))::text,
  g,
  timestamptz '2024-01-01' + (g % 730) * interval '1 day' + (g % 86400) * interval '1 second',
  timestamptz '2024-01-01' + (g % 730) * interval '1 day',
  CASE WHEN g % 7 = 0 THEN 'audit' ELSE 'permanent' END,
  '{"field":"status","newCategory":"Done"}'::jsonb
FROM generate_series(1, 600000) AS g;

INSERT INTO event_references (event_record_id, role, entity_type, entity_id)
SELECT id, 'scope', 'project', (1 + (id % 10))::text FROM event_records;

INSERT INTO event_references (event_record_id, role, entity_type, entity_id)
SELECT id, 'scope', 'sprint', (1 + (id % 200))::text
FROM event_records WHERE subject_type = 'sprint';

ANALYZE event_records;
ANALYZE event_references;

\echo '==== flow (single project) ===='
EXPLAIN (ANALYZE, BUFFERS, SUMMARY OFF)
SELECT e.*
FROM event_records e
WHERE e.workspace_id = 1
  AND e.occurred_at >= timestamptz '2024-06-01' AND e.occurred_at <= timestamptz '2024-09-01'
  AND EXISTS (SELECT 1 FROM event_references r
              WHERE r.event_record_id = e.id AND r.entity_type = 'project' AND r.entity_id = '5')
ORDER BY e.occurred_at, e.id;

\echo '==== burndown (UNION, as rewritten in ReportingRepository.GetBurndown) ===='
EXPLAIN (ANALYZE, BUFFERS, SUMMARY OFF)
SELECT u.id, u.occurred_at FROM (
  SELECT e.id, e.occurred_at FROM event_records e
  WHERE e.workspace_id = 1
    AND e.occurred_at >= timestamptz '2024-01-01' AND e.occurred_at <= timestamptz '2025-12-31'
    AND e.subject_type = 'sprint' AND e.subject_id = '42'
  UNION
  SELECT e.id, e.occurred_at FROM event_records e
  JOIN event_references r ON r.event_record_id = e.id
  WHERE e.workspace_id = 1
    AND e.occurred_at >= timestamptz '2024-01-01' AND e.occurred_at <= timestamptz '2025-12-31'
    AND r.entity_type = 'sprint' AND r.entity_id = '42'
) u
ORDER BY u.occurred_at, u.id;

\echo '==== coverageStart (all-projects case still scans workspace permanent events) ===='
EXPLAIN (ANALYZE, BUFFERS, SUMMARY OFF)
SELECT MIN(e.occurred_at)
FROM event_records e
WHERE e.workspace_id = 1 AND e.retention_class = 'permanent'
  AND EXISTS (SELECT 1 FROM event_references r
              WHERE r.event_record_id = e.id AND r.entity_type = 'project'
                AND r.entity_id = ANY (ARRAY['1','2','3','4','5','6','7','8','9','10']));
