<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="Anthropic" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="OpenAI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Netptune.Core\Netptune.Core.csproj" />
    <ProjectReference Include="..\Netptune.Transfer\Netptune.Transfer.csproj" />
    <ProjectReference Include="..\Netptune.Handlers\Netptune.Handlers.csproj" />
  </ItemGroup>

</Project>
