{{- if .Values.prometheus.enabled }}
---
apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "prometheus-ingress"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "prometheus"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.headlamp.host }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.headlamp.host }}/oauth2/sign_in?rd=https://$host$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User,X-Auth-Request-Email"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - "{{ .Values.prometheus.host }}"
      secretName: "prometheus-tls"
  rules:
    - host: "{{ .Values.prometheus.host }}"
      http:
        paths:
          - path: "/"
            pathType: "Prefix"
            backend:
              service:
                name: "prometheus-service"
                port:
                  number: 9090
{{- end }}
