{{- if .Values.prometheus.enabled }}
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "prometheus"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "prometheus"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
{{- end }}
