---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "public-api-secrets"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "public-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__cache: "cache-service:6379,password={{ .Values.secrets.publicApi.cache_password }}"
  CACHE_PASSWORD: "{{ .Values.secrets.publicApi.cache_password }}"
  CACHE_URI: "valkey://:{{ .Values.secrets.publicApi.cache_password }}@cache-service:6379"
  REDIS_URL: "cache-service:6379,password={{ .Values.secrets.publicApi.cache_password }}"
  ConnectionStrings__postgresdb: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.publicApi.postgres_password }};Database=netptune"
  POSTGRESDB_PASSWORD: "{{ .Values.secrets.publicApi.postgres_password }}"
  POSTGRESDB_URI: "postgresql://postgres:{{ .Values.secrets.publicApi.postgres_password }}@postgres-service:5432/netptune"
  ConnectionStrings__netptune: "Host=postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.publicApi.postgres_password }};Database=netptune"
{{- if .Values.aspire.enabled }}
  OTEL_EXPORTER_OTLP_HEADERS: "x-otlp-api-key={{ .Values.secrets.aspire.otlp_api_key }}"
{{- end }}
type: "Opaque"
