<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Netptune.Transfer\Netptune.Transfer.csproj" />
    <ProjectReference Include="..\Netptune.Query\Netptune.Query.csproj" />
    <ProjectReference Include="..\Netptune.Activity\Netptune.Activity.csproj" />
    <ProjectReference Include="..\Netptune.Ai\Netptune.Ai.csproj" />
    <ProjectReference Include="..\Netptune.Automation\Netptune.Automation.csproj" />
    <ProjectReference Include="..\Netptune.App\Netptune.App.csproj" />
    <ProjectReference Include="..\Netptune.Handlers\Netptune.Handlers.csproj" />
    <ProjectReference Include="..\Netptune.Messaging\Netptune.Messaging.csproj" />
    <ProjectReference Include="..\Netptune.Identity\Netptune.Identity.csproj" />
    <ProjectReference Include="..\Netptune.Services\Netptune.Services.csproj" />
    <ProjectReference Include="..\Netptune.Export\Netptune.Export.csproj" />
    <ProjectReference Include="..\Netptune.Import\Netptune.Import.csproj" />
    <ProjectReference Include="..\Netptune.TestData\Netptune.TestData.csproj" />
  </ItemGroup>

</Project>
