{{- if .Values.aspire.enabled }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "aspire-dashboard-secrets"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "aspire-dashboard"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  Dashboard__Otlp__PrimaryApiKey: "{{ .Values.secrets.aspire.otlp_api_key }}"
type: "Opaque"
{{- end }}
