{{- if .Values.headlamp.enabled }}
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "headlamp-kubeconfig"
  labels:
    app.kubernetes.io/name: "netptune-app"
    app.kubernetes.io/component: "headlamp"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: in-cluster
      cluster:
        server: https://kubernetes.default.svc
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
    - name: headlamp-sa
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - name: in-cluster
      context:
        cluster: in-cluster
        user: headlamp-sa
    current-context: in-cluster
{{- end }}
