name: Build Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Add ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      -
        name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: server/global.json
      -
        name: Install dependencies
        working-directory: ./server
        run: dotnet restore
      -
        name: Build
        working-directory: ./server
        run: dotnet build --configuration Release --no-restore
      -
        name: Run Unit Tests
        working-directory: ./server/Netptune.UnitTests
        run: dotnet test --configuration Release --no-restore
      -
        name: Run Integration Tests
        working-directory: ./server/Netptune.IntegrationTests
        run: dotnet test --configuration Release --no-restore
      -
        name: Build Image
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          BUILD_NUMBER=$(date '+%Y%m%d')
          docker build \
          --build-arg "COMMIT=${GITHUB_SHA}" \
          --build-arg "GITHUB_REF=${GITHUB_REF}" \
          --build-arg "BUILD_NUMBER=${BUILD_NUMBER}.${GITHUB_RUN_NUMBER}" \
          --build-arg "RUN_ID=${GITHUB_RUN_ID}" \
          -t dokku/netptune:$GITHUB_SHA .
          docker save dokku/netptune:$GITHUB_SHA | bzip2 | ssh $DOKKU_HOST "bunzip2 | docker load"
      -
        name: Deploy Image
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          ssh $DOKKU_HOST "dokku git:from-image netptune dokku/netptune:$GITHUB_SHA"
      -
        name: Build Jobs Image
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          BUILD_NUMBER=$(date '+%Y%m%d')
          docker build \
          --build-arg "COMMIT=${GITHUB_SHA}" \
          --build-arg "GITHUB_REF=${GITHUB_REF}" \
          --build-arg "BUILD_NUMBER=${BUILD_NUMBER}.${GITHUB_RUN_NUMBER}" \
          --build-arg "RUN_ID=${GITHUB_RUN_ID}" \
          -t dokku/netptune-jobs:$GITHUB_SHA -f Dockerfile.jobs .
          docker save dokku/netptune-jobs:$GITHUB_SHA | bzip2 | ssh $DOKKU_HOST "bunzip2 | docker load"
      -
        name: Deploy Jobs Image
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          ssh $DOKKU_HOST "dokku git:from-image netptune-jobs dokku/netptune-jobs:$GITHUB_SHA"
