name: Build Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      -
        name: Install Deps
        run: |
          apt -y install docker.io
      -
        name: Build
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          BUILD_NUMBER=$(date '+%Y%m%d')
          docker build \
          --build-arg "COMMIT=${GITHUB_SHA}" \
          --build-arg "GITHUB_REF=${GITHUB_REF}" \
          --build-arg "BUILD_NUMBER=${BUILD_NUMBER}.${GITHUB_RUN_NUMBER}" \
          --build-arg "RUN_ID=${GITHUB_RUN_ID}" \
          -t dokku/netptune:$GITHUB_SHA .
          docker save dokku/netptune:$GITHUB_SHA | bzip2 | ssh $DOKKU_HOST "bunzip2 | docker load"
      -
        name: Deploy
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          ssh $DOKKU_HOST "dokku git:from-image netptune dokku/netptune:$GITHUB_SHA"
