name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      -
        name: Build
        run: |
          docker build -t dokku/netptune:ci .
      -
        name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      -
        name: Push
        env:
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          docker save dokku/netptune:ci | ssh $DOKKU_HOST "docker load; dokku tags:create netptune previous; dokku tags:deploy netptune ci && dokku tags:create netptune latest"
