name: Deploy

on:
  workflow_run:
    workflows:
      - Build App Image
      - Build Client Image
      - Build Jobs Image
    branches: [main]
    types: [completed]
  push:
    branches: [main]
    paths:
      - "charts/**"
      - ".github/workflows/deploy-charts.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v5

      - name: Set up kubectl
        uses: azure/setup-kubectl@v5

      - name: Write kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_PROD }}" > kubeconfig.yaml

      - name: Deploy
        run: |
          helm upgrade netptune-app charts/netptune/ \
            --kubeconfig kubeconfig.yaml \
            --namespace default \
            --set ingress.enabled=true \
            --set "ingress.host=netptune.co.uk" \
            --set ingress.tls.enabled=true \
            --set "ingress.tls.email=${{ secrets.TLS_EMAIL }}" \
            --set "parameters.client.api_url=http://api-service:7400" \
            --set "secrets.postgres.postgres_password=${{ secrets.POSTGRES_PASSWORD }}" \
            --set "secrets.cache.cache_password=${{ secrets.CACHE_PASSWORD }}" \
            --set "secrets.api.cache_password=${{ secrets.CACHE_PASSWORD }}" \
            --set "secrets.api.postgres_password=${{ secrets.POSTGRES_PASSWORD }}" \
            --set "secrets.api.signing_key=${{ secrets.SIGNING_KEY }}" \
            --set "secrets.api.github_client_id=${{ secrets.APP_GITHUB_CLIENT_ID }}" \
            --set "secrets.api.github_secret=${{ secrets.APP_GITHUB_SECRET }}" \
            --set "secrets.api.github_callback=${{ secrets.APP_GITHUB_CALLBACK }}" \
            --set "secrets.api.sendgrid_api_key=${{ secrets.SENDGRID_API_KEY }}" \
            --set "secrets.api.s3_bucket_name=${{ secrets.S3_BUCKET_NAME }}" \
            --set "secrets.api.s3_region=${{ secrets.S3_REGION }}" \
            --set "secrets.api.s3_access_key_id=${{ secrets.S3_ACCESS_KEY_ID }}" \
            --set "secrets.api.s3_secret_access_key=${{ secrets.S3_SECRET_ACCESS_KEY }}" \
            --set "secrets.api.turnstile_secret_key=${{ secrets.NETPTUNE_TURNSTILE_SECRET_KEY }}" \
            --set "secrets.api.cloudflare_email_token=${{ secrets.NETPTUNE_CLOUDFLARE_EMAIL_TOKEN }}" \
            --set "secrets.api.cloudflare_account_id=${{ secrets.NETPTUNE_CLOUDFLARE_ACCOUNT_ID }}" \
            --set "secrets.jobs.cache_password=${{ secrets.CACHE_PASSWORD }}" \
            --set "secrets.jobs.postgres_password=${{ secrets.POSTGRES_PASSWORD }}" \
            --set "secrets.jobs.signing_key=${{ secrets.SIGNING_KEY }}" \
            --set "secrets.jobs.sendgrid_api_key=${{ secrets.SENDGRID_API_KEY }}" \
            --set "secrets.jobs.s3_bucket_name=${{ secrets.S3_BUCKET_NAME }}" \
            --set "secrets.jobs.s3_region=${{ secrets.S3_REGION }}" \
            --set "secrets.jobs.s3_access_key_id=${{ secrets.S3_ACCESS_KEY_ID }}" \
            --set "secrets.jobs.s3_secret_access_key=${{ secrets.S3_SECRET_ACCESS_KEY }}" \
            --set "secrets.jobs.cloudflare_email_token=${{ secrets.NETPTUNE_CLOUDFLARE_EMAIL_TOKEN }}" \
            --set "secrets.jobs.cloudflare_account_id=${{ secrets.NETPTUNE_CLOUDFLARE_ACCOUNT_ID }}" \
            --set "secrets.headlamp.github_client_id=${{ secrets.HEADLAMP_GITHUB_CLIENT_ID }}" \
            --set "secrets.headlamp.github_client_secret=${{ secrets.HEADLAMP_GITHUB_CLIENT_SECRET }}" \
            --set "secrets.headlamp.cookie_secret=${{ secrets.HEADLAMP_COOKIE_SECRET }}" \
            --set "secrets.grafana.admin_password=${{ secrets.GRAFANA_ADMIN_PASSWORD }}"

      - name: Restart deployments
        run: |
          kubectl --kubeconfig kubeconfig.yaml rollout restart deployment/api-deployment deployment/jobs-deployment deployment/client-deployment
          kubectl --kubeconfig kubeconfig.yaml rollout status deployment/api-deployment deployment/jobs-deployment deployment/client-deployment
